### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by tsuyori-S** [tsuyori-S/protospace-37747#1]
# URL
https://protospace-37747.herokuapp.com/

**Comment by shodai-ito** [comment]
@tsuyori-S さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
`プロトタイプ編集機能`
- [ ] **バリデーションによって投稿ができず、そのページに留まった場合でも、入力済みの項目（画像以外）は消えないこと**
一度編集に失敗すると、正しい項目も全て消えてしまいます。

`コメント機能`
- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のフォームを送信するとエラーになってしまいます。
<img width="709" alt="スクリーンショット 2022-04-14 9 17 04" src="https://user-images.githubusercontent.com/62537107/163290515-398c7a2c-71f1-4341-842e-a9f9bd8629d0.png">

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by tsuyori-S** [comment]
ご確認いただきありがとうございます。
ご指摘いただいた点を修正しましたので、再度チェックをお願いいたします。

**Comment by shodai-ito** [comment]
@tsuyori-S さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください。
